{% if os.getenv('LOCAL_AMBERTOOLS', "") %}
    # e.g:
    # - export LOCAL_AMBERTOOLS="file:///home/haichit/AmberTools16.tar.bz2"
    # - export LOCAL_AMBERTOOLS="/home/haichit/amber16/"
    {% set ambertools_url = os.getenv('LOCAL_AMBERTOOLS') %}
{% else %}
    # Please update your name and other info if you maintain or update this recipe
    # {% set ambertools_url = "http://ambermd.org/cgi-bin/AmberTools16-get.pl?Name=HaiNguyen&Institution=Rutgers&City=NewBrunswicks&State=NJ&Country=USA" %}
    {% set ambertools_url = "https://dl.dropboxusercontent.com/u/5494759/at17.28dec16.tar.bz2" %}
{% endif %}

{% set version = "17" %}
{% set bugfix_version = "0" %} # applied update.1  to update.{{bugfix_version}}
{% set build_number = "1" %} # e.g: add Amber16.pdf, add some library (xleap)
{% set ambertools_version = version + '.' + bugfix_version + '.' + build_number %}
{% set ambertools_fn = "AmberTools" + version + ".tar.bz2" %}

# AMBER_BUILD_TASK = {'', 'ambermini', 'ambertools'}
{% if os.getenv('AMBER_BUILD_TASK', 'ambermini') == 'ambermini' %}
     {%set ambertools_package = 'ambermini101' %}
     {% set summary = "ambermini101, a subset of AmberTools" %}
{% else %}
     {%set ambertools_package = 'ambertools' %}
     {% set summary = "AmberTools is a set of programs for biomolecular simulation and analysis." %}
{% endif %}

package:
  name: {{ ambertools_package }}
  version: {{ ambertools_version }}

source:
  fn : {{ ambertools_fn }}
  url : {{ ambertools_url }}
  
build:
  number: {{ build_number }}
  script_env:
    - AMBER_BUILD_TASK
    - LOCAL_AMBERTOOLS

requirements:
  build:
    - zlib
    - bzip2
    - python
    - mingwpy [win]
  run:
    - zlib
    - bzip2
    - python
    - requests

about:
    home: https://ambermd.org
    license: GNU General Public License (GPL)
    summary: {{ summary }}
