matrix:
  include:
    - { os: linux }
    - { os: osx }
language: cpp
sudo: required
services: docker
install:
    - source setup.sh
script: echo "hello"
after_success:
    - docker images
notifications:
  email: false
