sudo: true
language: cpp
addons:
  apt:
    sources:
    - ubuntu-precise
    packages:
      - gfortran
      - libbz2-dev
      - libblas-dev
      - liblapack-dev
      - libarpack2-dev
      - libnetcdf-dev
      - libfftw3-dev
      - netcdf-bin
      - clang
      - openmpi-bin
      - openmpi-common
      - libopenmpi-dev
matrix:
  include:
   - { os: osx, env: AMBER_BUILD_TASK=ambermini }
   - { os: osx, env: AMBER_BUILD_TASK=ambertools }
   - { os: linux, env: AMBER_BUILD_TASK=ambermini }
   - { os: linux, env: AMBER_BUILD_TASK=ambertools }
install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          brew tap homebrew/science;
          brew update;
          brew install gcc;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          sudo apt-get install -y csh;
      fi
    - source scripts/install_miniconda.sh
    - conda build recipe
script: echo "hello"
after_success:
    - echo "hello"
notifications:
  email: false
